### ISSUE TITLE
TypeError: getCellWidth is not a function  after update to 2.0.5

### ISSUE THREAD

**Issue by maximenathan** [DevExpress/devextreme-reactive#2351]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

After updating to `devexpress/dx-react-core`, `devexpress/dx-react-grid` and `dx-react-grid-material-ui` I got the following errors :

![image](https://user-images.githubusercontent.com/7127156/65497634-d4facb80-deba-11e9-8d4d-2ff1aa338dda.png)

![image](https://user-images.githubusercontent.com/7127156/65497684-e93ec880-deba-11e9-84d3-26fac4bacbfc.png)

The error disappears when:

- I downgrade  `dx-react-grid-material-ui` to 2.0.4
- If I don't use  `TableHeaderRow` from `@devexpress/dx-react-grid-material-ui`
- If I don't use a custom TableHeaderRow `cellComponent` 

I tried to reproduce my error on [codesandbox](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-x4mmp) box but I got another error before using a custom cellComponent

Do you need any more information?

Thank you

### Environment

- react: 19.9.0
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.4.2
